- id: '1727716571707'
  alias: App - Lock door
  description: ''
  trigger:
  - event_type: ios.action_fired
    platform: event
    event_data:
      actionID: 23157A7D-6931-485B-A4E3-23E3B0F3226C
  condition: []
  action:
  - action: lock.lock
    metadata: {}
    data: {}
    target:
      entity_id: lock.voordeur
  mode: single
- id: '1727716714681'
  alias: App - Open door
  description: ''
  trigger:
  - event_data:
      actionID: 28C02FBA-55CB-4421-BD32-E8BBB2056210
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - action: lock.unlock
    target:
      entity_id: lock.voordeur
    data: {}
  mode: single
- id: '1732692880064'
  alias: Telegram HVC Notification
  description: Send a notification when there is a garbage collection
  triggers:
  - at: '19:00:00'
    trigger: time
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.hvc_restafval
      attribute: day
      state: Morgen
    - condition: state
      entity_id: sensor.hvc_gft
      attribute: day
      state: Morgen
    - condition: state
      entity_id: sensor.hvc_plastic
      attribute: day
      state: Morgen
    - condition: state
      entity_id: sensor.hvc_papier
      attribute: day
      state: Morgen
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.hvc_restafval
        attribute: day
        state: Morgen
      sequence:
      - data:
          title: HVC
          message: 'Morgen komt Restafval, vergeet de bak niet aan de weg te zetten!

            '
        action: notify.mobile_app_nimbus_2000
    - conditions:
      - condition: state
        entity_id: sensor.hvc_gft
        attribute: day
        state: Morgen
      sequence:
      - data:
          title: HVC
          message: 'Morgen komt GFT, vergeet de bak niet aan de weg te zetten!

            '
        action: notify.mobile_app_nimbus_2000
    - conditions:
      - condition: state
        entity_id: sensor.hvc_plastic
        attribute: day
        state: Morgen
      sequence:
      - data:
          title: HVC
          message: 'Morgen komt Plastic, vergeet de bak niet aan de weg te zetten!

            '
        action: notify.mobile_app_nimbus_2000
    - conditions:
      - condition: state
        entity_id: sensor.hvc_papier
        attribute: day
        state: Morgen
      sequence:
      - data:
          title: HVC
          message: 'Morgen komt Oud Papier, vergeet het niet aan de weg te zetten!

            '
        action: notify.mobile_app_nimbus_2000
  mode: single
  max_exceeded: silent
