---
#
# Binary sensor to check that my kids stay with me.
#
trigger:
  - platform: time_pattern
    minutes: /10
action:
  - service: calendar.get_events
    data:
      duration:
        hours: 6
    target:
      entity_id: calendar.kinderen
    response_variable: agenda
binary_sensor:
  - unique_id: template_binary_kinderen_papa
    name: Kinderen Papa
    device_class: presence
    state: |-
      {{ 
        agenda['calendar.kinderen'].events 
        | selectattr('summary', 'match', "^papa$", ignorecase=true)
        | list 
        | count > 0 
      }}
    availability: |-
      {{ 
        (
          (
            agenda['calendar.kinderen'].events
            | selectattr('summary', 'match', "^papa$", ignorecase=true)
            | list
          )
          +
          (
            agenda['calendar.kinderen'].events
            | selectattr('summary', 'match', '^mama$', ignorecase=true)
            | list
          )
        )
        | count > 0
      }}
